/* This file is auto-generated by gen_dump_gpu_metrics_h.awk. */

#include <stdio.h>
#include "dump_gpu_metrics.h"

static const char __tableHeader[] =
"|              Name              |      Value      |\n"
"|--------------------------------|-----------------|\n";
static const char __tableFormat[] = "| %-30s | %15llu |\n";
static const char __subStructFormat[] = "| %-30s | %-15s |\n";

static void __dump_amdgpu_xcp_metrics(const struct amdgpu_xcp_metrics *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	/* Utilization Instantaneous (%) */
	for (unsigned i = 0; i < MAX_XCC; i++)
	{
		sprintf(buf, "gfx_busy_inst[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->gfx_busy_inst[i]);
	}
	for (unsigned i = 0; i < NUM_JPEG_ENG; i++)
	{
		sprintf(buf, "jpeg_busy[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->jpeg_busy[i]);
	}
	for (unsigned i = 0; i < NUM_VCN; i++)
	{
		sprintf(buf, "vcn_busy[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->vcn_busy[i]);
	}
	/* Utilization Accumulated (%) */
	for (unsigned i = 0; i < MAX_XCC; i++)
	{
		sprintf(buf, "gfx_busy_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->gfx_busy_acc[i]);
	}
}

static void __dump_amdgpu_xcp_metrics_v1_1(const struct amdgpu_xcp_metrics_v1_1 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	/* Utilization Instantaneous (%) */
	for (unsigned i = 0; i < MAX_XCC; i++)
	{
		sprintf(buf, "gfx_busy_inst[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->gfx_busy_inst[i]);
	}
	for (unsigned i = 0; i < NUM_JPEG_ENG; i++)
	{
		sprintf(buf, "jpeg_busy[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->jpeg_busy[i]);
	}
	for (unsigned i = 0; i < NUM_VCN; i++)
	{
		sprintf(buf, "vcn_busy[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->vcn_busy[i]);
	}
	/* Utilization Accumulated (%) */
	for (unsigned i = 0; i < MAX_XCC; i++)
	{
		sprintf(buf, "gfx_busy_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->gfx_busy_acc[i]);
	}
	/* Total App Clock Counter Accumulated */
	for (unsigned i = 0; i < MAX_XCC; i++)
	{
		sprintf(buf, "gfx_below_host_limit_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->gfx_below_host_limit_acc[i]);
	}
}

static void __dump_amdgpu_xcp_metrics_v1_2(const struct amdgpu_xcp_metrics_v1_2 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	/* Utilization Instantaneous (%) */
	for (unsigned i = 0; i < MAX_XCC; i++)
	{
		sprintf(buf, "gfx_busy_inst[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->gfx_busy_inst[i]);
	}
	for (unsigned i = 0; i < NUM_JPEG_ENG_V1; i++)
	{
		sprintf(buf, "jpeg_busy[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->jpeg_busy[i]);
	}
	for (unsigned i = 0; i < NUM_VCN; i++)
	{
		sprintf(buf, "vcn_busy[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->vcn_busy[i]);
	}
	/* Utilization Accumulated (%) */
	for (unsigned i = 0; i < MAX_XCC; i++)
	{
		sprintf(buf, "gfx_busy_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->gfx_busy_acc[i]);
	}
	/* Total App Clock Counter Accumulated */
	for (unsigned i = 0; i < MAX_XCC; i++)
	{
		sprintf(buf, "gfx_below_host_limit_ppt_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->gfx_below_host_limit_ppt_acc[i]);
	}
	for (unsigned i = 0; i < MAX_XCC; i++)
	{
		sprintf(buf, "gfx_below_host_limit_thm_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->gfx_below_host_limit_thm_acc[i]);
	}
	for (unsigned i = 0; i < MAX_XCC; i++)
	{
		sprintf(buf, "gfx_low_utilization_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->gfx_low_utilization_acc[i]);
	}
	for (unsigned i = 0; i < MAX_XCC; i++)
	{
		sprintf(buf, "gfx_below_host_limit_total_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->gfx_below_host_limit_total_acc[i]);
	}
}

static void __dump_metrics_table_header(const struct metrics_table_header *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	printf(__tableFormat, "structure_size", (unsigned long long)metrics->structure_size);
	printf(__tableFormat, "format_revision", (unsigned long long)metrics->format_revision);
	printf(__tableFormat, "content_revision", (unsigned long long)metrics->content_revision);
}

static void __dump_gpu_metrics_v1_0(const struct gpu_metrics_v1_0 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	printf(__subStructFormat, "metrics_table_header", "common_header {");
	__dump_metrics_table_header(&metrics->common_header);
	printf(__subStructFormat, "", "}");

	/* Driver attached timestamp (in ns) */
	printf(__tableFormat, "system_clock_counter", (unsigned long long)metrics->system_clock_counter);

	/* Temperature */
	printf(__tableFormat, "temperature_edge", (unsigned long long)metrics->temperature_edge);
	printf(__tableFormat, "temperature_hotspot", (unsigned long long)metrics->temperature_hotspot);
	printf(__tableFormat, "temperature_mem", (unsigned long long)metrics->temperature_mem);
	printf(__tableFormat, "temperature_vrgfx", (unsigned long long)metrics->temperature_vrgfx);
	printf(__tableFormat, "temperature_vrsoc", (unsigned long long)metrics->temperature_vrsoc);
	printf(__tableFormat, "temperature_vrmem", (unsigned long long)metrics->temperature_vrmem);

	/* Utilization */
	printf(__tableFormat, "average_gfx_activity", (unsigned long long)metrics->average_gfx_activity);
	printf(__tableFormat, "average_umc_activity", (unsigned long long)metrics->average_umc_activity); // memory controller
	printf(__tableFormat, "average_mm_activity", (unsigned long long)metrics->average_mm_activity); // UVD or VCN

	/* Power/Energy */
	printf(__tableFormat, "average_socket_power", (unsigned long long)metrics->average_socket_power);
	printf(__tableFormat, "energy_accumulator", (unsigned long long)metrics->energy_accumulator);

	/* Average clocks */
	printf(__tableFormat, "average_gfxclk_frequency", (unsigned long long)metrics->average_gfxclk_frequency);
	printf(__tableFormat, "average_socclk_frequency", (unsigned long long)metrics->average_socclk_frequency);
	printf(__tableFormat, "average_uclk_frequency", (unsigned long long)metrics->average_uclk_frequency);
	printf(__tableFormat, "average_vclk0_frequency", (unsigned long long)metrics->average_vclk0_frequency);
	printf(__tableFormat, "average_dclk0_frequency", (unsigned long long)metrics->average_dclk0_frequency);
	printf(__tableFormat, "average_vclk1_frequency", (unsigned long long)metrics->average_vclk1_frequency);
	printf(__tableFormat, "average_dclk1_frequency", (unsigned long long)metrics->average_dclk1_frequency);

	/* Current clocks */
	printf(__tableFormat, "current_gfxclk", (unsigned long long)metrics->current_gfxclk);
	printf(__tableFormat, "current_socclk", (unsigned long long)metrics->current_socclk);
	printf(__tableFormat, "current_uclk", (unsigned long long)metrics->current_uclk);
	printf(__tableFormat, "current_vclk0", (unsigned long long)metrics->current_vclk0);
	printf(__tableFormat, "current_dclk0", (unsigned long long)metrics->current_dclk0);
	printf(__tableFormat, "current_vclk1", (unsigned long long)metrics->current_vclk1);
	printf(__tableFormat, "current_dclk1", (unsigned long long)metrics->current_dclk1);

	/* Throttle status */
	printf(__tableFormat, "throttle_status", (unsigned long long)metrics->throttle_status);

	/* Fans */
	printf(__tableFormat, "current_fan_speed", (unsigned long long)metrics->current_fan_speed);

	/* Link width/speed */
	printf(__tableFormat, "pcie_link_width", (unsigned long long)metrics->pcie_link_width);
	printf(__tableFormat, "pcie_link_speed", (unsigned long long)metrics->pcie_link_speed); // in 0.1 GT/s
}

static void __dump_gpu_metrics_v1_1(const struct gpu_metrics_v1_1 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	printf(__subStructFormat, "metrics_table_header", "common_header {");
	__dump_metrics_table_header(&metrics->common_header);
	printf(__subStructFormat, "", "}");

	/* Temperature */
	printf(__tableFormat, "temperature_edge", (unsigned long long)metrics->temperature_edge);
	printf(__tableFormat, "temperature_hotspot", (unsigned long long)metrics->temperature_hotspot);
	printf(__tableFormat, "temperature_mem", (unsigned long long)metrics->temperature_mem);
	printf(__tableFormat, "temperature_vrgfx", (unsigned long long)metrics->temperature_vrgfx);
	printf(__tableFormat, "temperature_vrsoc", (unsigned long long)metrics->temperature_vrsoc);
	printf(__tableFormat, "temperature_vrmem", (unsigned long long)metrics->temperature_vrmem);

	/* Utilization */
	printf(__tableFormat, "average_gfx_activity", (unsigned long long)metrics->average_gfx_activity);
	printf(__tableFormat, "average_umc_activity", (unsigned long long)metrics->average_umc_activity); // memory controller
	printf(__tableFormat, "average_mm_activity", (unsigned long long)metrics->average_mm_activity); // UVD or VCN

	/* Power/Energy */
	printf(__tableFormat, "average_socket_power", (unsigned long long)metrics->average_socket_power);
	printf(__tableFormat, "energy_accumulator", (unsigned long long)metrics->energy_accumulator);

	/* Driver attached timestamp (in ns) */
	printf(__tableFormat, "system_clock_counter", (unsigned long long)metrics->system_clock_counter);

	/* Average clocks */
	printf(__tableFormat, "average_gfxclk_frequency", (unsigned long long)metrics->average_gfxclk_frequency);
	printf(__tableFormat, "average_socclk_frequency", (unsigned long long)metrics->average_socclk_frequency);
	printf(__tableFormat, "average_uclk_frequency", (unsigned long long)metrics->average_uclk_frequency);
	printf(__tableFormat, "average_vclk0_frequency", (unsigned long long)metrics->average_vclk0_frequency);
	printf(__tableFormat, "average_dclk0_frequency", (unsigned long long)metrics->average_dclk0_frequency);
	printf(__tableFormat, "average_vclk1_frequency", (unsigned long long)metrics->average_vclk1_frequency);
	printf(__tableFormat, "average_dclk1_frequency", (unsigned long long)metrics->average_dclk1_frequency);

	/* Current clocks */
	printf(__tableFormat, "current_gfxclk", (unsigned long long)metrics->current_gfxclk);
	printf(__tableFormat, "current_socclk", (unsigned long long)metrics->current_socclk);
	printf(__tableFormat, "current_uclk", (unsigned long long)metrics->current_uclk);
	printf(__tableFormat, "current_vclk0", (unsigned long long)metrics->current_vclk0);
	printf(__tableFormat, "current_dclk0", (unsigned long long)metrics->current_dclk0);
	printf(__tableFormat, "current_vclk1", (unsigned long long)metrics->current_vclk1);
	printf(__tableFormat, "current_dclk1", (unsigned long long)metrics->current_dclk1);

	/* Throttle status */
	printf(__tableFormat, "throttle_status", (unsigned long long)metrics->throttle_status);

	/* Fans */
	printf(__tableFormat, "current_fan_speed", (unsigned long long)metrics->current_fan_speed);

	/* Link width/speed */
	printf(__tableFormat, "pcie_link_width", (unsigned long long)metrics->pcie_link_width);
	printf(__tableFormat, "pcie_link_speed", (unsigned long long)metrics->pcie_link_speed); // in 0.1 GT/s

	printf(__tableFormat, "padding", (unsigned long long)metrics->padding);

	printf(__tableFormat, "gfx_activity_acc", (unsigned long long)metrics->gfx_activity_acc);
	printf(__tableFormat, "mem_activity_acc", (unsigned long long)metrics->mem_activity_acc);

	for (unsigned i = 0; i < NUM_HBM_INSTANCES; i++)
	{
		sprintf(buf, "temperature_hbm[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->temperature_hbm[i]);
	}
}

static void __dump_gpu_metrics_v1_2(const struct gpu_metrics_v1_2 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	printf(__subStructFormat, "metrics_table_header", "common_header {");
	__dump_metrics_table_header(&metrics->common_header);
	printf(__subStructFormat, "", "}");

	/* Temperature */
	printf(__tableFormat, "temperature_edge", (unsigned long long)metrics->temperature_edge);
	printf(__tableFormat, "temperature_hotspot", (unsigned long long)metrics->temperature_hotspot);
	printf(__tableFormat, "temperature_mem", (unsigned long long)metrics->temperature_mem);
	printf(__tableFormat, "temperature_vrgfx", (unsigned long long)metrics->temperature_vrgfx);
	printf(__tableFormat, "temperature_vrsoc", (unsigned long long)metrics->temperature_vrsoc);
	printf(__tableFormat, "temperature_vrmem", (unsigned long long)metrics->temperature_vrmem);

	/* Utilization */
	printf(__tableFormat, "average_gfx_activity", (unsigned long long)metrics->average_gfx_activity);
	printf(__tableFormat, "average_umc_activity", (unsigned long long)metrics->average_umc_activity); // memory controller
	printf(__tableFormat, "average_mm_activity", (unsigned long long)metrics->average_mm_activity); // UVD or VCN

	/* Power/Energy */
	printf(__tableFormat, "average_socket_power", (unsigned long long)metrics->average_socket_power);
	printf(__tableFormat, "energy_accumulator", (unsigned long long)metrics->energy_accumulator);

	/* Driver attached timestamp (in ns) */
	printf(__tableFormat, "system_clock_counter", (unsigned long long)metrics->system_clock_counter);

	/* Average clocks */
	printf(__tableFormat, "average_gfxclk_frequency", (unsigned long long)metrics->average_gfxclk_frequency);
	printf(__tableFormat, "average_socclk_frequency", (unsigned long long)metrics->average_socclk_frequency);
	printf(__tableFormat, "average_uclk_frequency", (unsigned long long)metrics->average_uclk_frequency);
	printf(__tableFormat, "average_vclk0_frequency", (unsigned long long)metrics->average_vclk0_frequency);
	printf(__tableFormat, "average_dclk0_frequency", (unsigned long long)metrics->average_dclk0_frequency);
	printf(__tableFormat, "average_vclk1_frequency", (unsigned long long)metrics->average_vclk1_frequency);
	printf(__tableFormat, "average_dclk1_frequency", (unsigned long long)metrics->average_dclk1_frequency);

	/* Current clocks */
	printf(__tableFormat, "current_gfxclk", (unsigned long long)metrics->current_gfxclk);
	printf(__tableFormat, "current_socclk", (unsigned long long)metrics->current_socclk);
	printf(__tableFormat, "current_uclk", (unsigned long long)metrics->current_uclk);
	printf(__tableFormat, "current_vclk0", (unsigned long long)metrics->current_vclk0);
	printf(__tableFormat, "current_dclk0", (unsigned long long)metrics->current_dclk0);
	printf(__tableFormat, "current_vclk1", (unsigned long long)metrics->current_vclk1);
	printf(__tableFormat, "current_dclk1", (unsigned long long)metrics->current_dclk1);

	/* Throttle status (ASIC dependent) */
	printf(__tableFormat, "throttle_status", (unsigned long long)metrics->throttle_status);

	/* Fans */
	printf(__tableFormat, "current_fan_speed", (unsigned long long)metrics->current_fan_speed);

	/* Link width/speed */
	printf(__tableFormat, "pcie_link_width", (unsigned long long)metrics->pcie_link_width);
	printf(__tableFormat, "pcie_link_speed", (unsigned long long)metrics->pcie_link_speed); // in 0.1 GT/s

	printf(__tableFormat, "padding", (unsigned long long)metrics->padding);

	printf(__tableFormat, "gfx_activity_acc", (unsigned long long)metrics->gfx_activity_acc);
	printf(__tableFormat, "mem_activity_acc", (unsigned long long)metrics->mem_activity_acc);

	for (unsigned i = 0; i < NUM_HBM_INSTANCES; i++)
	{
		sprintf(buf, "temperature_hbm[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->temperature_hbm[i]);
	}

	/* PMFW attached timestamp (10ns resolution) */
	printf(__tableFormat, "firmware_timestamp", (unsigned long long)metrics->firmware_timestamp);
}

static void __dump_gpu_metrics_v1_3(const struct gpu_metrics_v1_3 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	printf(__subStructFormat, "metrics_table_header", "common_header {");
	__dump_metrics_table_header(&metrics->common_header);
	printf(__subStructFormat, "", "}");

	/* Temperature */
	printf(__tableFormat, "temperature_edge", (unsigned long long)metrics->temperature_edge);
	printf(__tableFormat, "temperature_hotspot", (unsigned long long)metrics->temperature_hotspot);
	printf(__tableFormat, "temperature_mem", (unsigned long long)metrics->temperature_mem);
	printf(__tableFormat, "temperature_vrgfx", (unsigned long long)metrics->temperature_vrgfx);
	printf(__tableFormat, "temperature_vrsoc", (unsigned long long)metrics->temperature_vrsoc);
	printf(__tableFormat, "temperature_vrmem", (unsigned long long)metrics->temperature_vrmem);

	/* Utilization */
	printf(__tableFormat, "average_gfx_activity", (unsigned long long)metrics->average_gfx_activity);
	printf(__tableFormat, "average_umc_activity", (unsigned long long)metrics->average_umc_activity); // memory controller
	printf(__tableFormat, "average_mm_activity", (unsigned long long)metrics->average_mm_activity); // UVD or VCN

	/* Power/Energy */
	printf(__tableFormat, "average_socket_power", (unsigned long long)metrics->average_socket_power);
	printf(__tableFormat, "energy_accumulator", (unsigned long long)metrics->energy_accumulator);

	/* Driver attached timestamp (in ns) */
	printf(__tableFormat, "system_clock_counter", (unsigned long long)metrics->system_clock_counter);

	/* Average clocks */
	printf(__tableFormat, "average_gfxclk_frequency", (unsigned long long)metrics->average_gfxclk_frequency);
	printf(__tableFormat, "average_socclk_frequency", (unsigned long long)metrics->average_socclk_frequency);
	printf(__tableFormat, "average_uclk_frequency", (unsigned long long)metrics->average_uclk_frequency);
	printf(__tableFormat, "average_vclk0_frequency", (unsigned long long)metrics->average_vclk0_frequency);
	printf(__tableFormat, "average_dclk0_frequency", (unsigned long long)metrics->average_dclk0_frequency);
	printf(__tableFormat, "average_vclk1_frequency", (unsigned long long)metrics->average_vclk1_frequency);
	printf(__tableFormat, "average_dclk1_frequency", (unsigned long long)metrics->average_dclk1_frequency);

	/* Current clocks */
	printf(__tableFormat, "current_gfxclk", (unsigned long long)metrics->current_gfxclk);
	printf(__tableFormat, "current_socclk", (unsigned long long)metrics->current_socclk);
	printf(__tableFormat, "current_uclk", (unsigned long long)metrics->current_uclk);
	printf(__tableFormat, "current_vclk0", (unsigned long long)metrics->current_vclk0);
	printf(__tableFormat, "current_dclk0", (unsigned long long)metrics->current_dclk0);
	printf(__tableFormat, "current_vclk1", (unsigned long long)metrics->current_vclk1);
	printf(__tableFormat, "current_dclk1", (unsigned long long)metrics->current_dclk1);

	/* Throttle status */
	printf(__tableFormat, "throttle_status", (unsigned long long)metrics->throttle_status);

	/* Fans */
	printf(__tableFormat, "current_fan_speed", (unsigned long long)metrics->current_fan_speed);

	/* Link width/speed */
	printf(__tableFormat, "pcie_link_width", (unsigned long long)metrics->pcie_link_width);
	printf(__tableFormat, "pcie_link_speed", (unsigned long long)metrics->pcie_link_speed); // in 0.1 GT/s

	printf(__tableFormat, "padding", (unsigned long long)metrics->padding);

	printf(__tableFormat, "gfx_activity_acc", (unsigned long long)metrics->gfx_activity_acc);
	printf(__tableFormat, "mem_activity_acc", (unsigned long long)metrics->mem_activity_acc);

	for (unsigned i = 0; i < NUM_HBM_INSTANCES; i++)
	{
		sprintf(buf, "temperature_hbm[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->temperature_hbm[i]);
	}

	/* PMFW attached timestamp (10ns resolution) */
	printf(__tableFormat, "firmware_timestamp", (unsigned long long)metrics->firmware_timestamp);

	/* Voltage (mV) */
	printf(__tableFormat, "voltage_soc", (unsigned long long)metrics->voltage_soc);
	printf(__tableFormat, "voltage_gfx", (unsigned long long)metrics->voltage_gfx);
	printf(__tableFormat, "voltage_mem", (unsigned long long)metrics->voltage_mem);

	printf(__tableFormat, "padding1", (unsigned long long)metrics->padding1);

	/* Throttle status (ASIC independent) */
	printf(__tableFormat, "indep_throttle_status", (unsigned long long)metrics->indep_throttle_status);
}

static void __dump_gpu_metrics_v1_4(const struct gpu_metrics_v1_4 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	printf(__subStructFormat, "metrics_table_header", "common_header {");
	__dump_metrics_table_header(&metrics->common_header);
	printf(__subStructFormat, "", "}");

	/* Temperature (Celsius) */
	printf(__tableFormat, "temperature_hotspot", (unsigned long long)metrics->temperature_hotspot);
	printf(__tableFormat, "temperature_mem", (unsigned long long)metrics->temperature_mem);
	printf(__tableFormat, "temperature_vrsoc", (unsigned long long)metrics->temperature_vrsoc);

	/* Power (Watts) */
	printf(__tableFormat, "curr_socket_power", (unsigned long long)metrics->curr_socket_power);

	/* Utilization (%) */
	printf(__tableFormat, "average_gfx_activity", (unsigned long long)metrics->average_gfx_activity);
	printf(__tableFormat, "average_umc_activity", (unsigned long long)metrics->average_umc_activity); // memory controller
	for (unsigned i = 0; i < NUM_VCN; i++)
	{
		sprintf(buf, "vcn_activity[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->vcn_activity[i]);
	}

	/* Energy (15.259uJ (2^-16) units) */
	printf(__tableFormat, "energy_accumulator", (unsigned long long)metrics->energy_accumulator);

	/* Driver attached timestamp (in ns) */
	printf(__tableFormat, "system_clock_counter", (unsigned long long)metrics->system_clock_counter);

	/* Throttle status */
	printf(__tableFormat, "throttle_status", (unsigned long long)metrics->throttle_status);

	/* Clock Lock Status. Each bit corresponds to clock instance */
	printf(__tableFormat, "gfxclk_lock_status", (unsigned long long)metrics->gfxclk_lock_status);

	/* Link width (number of lanes) and speed (in 0.1 GT/s) */
	printf(__tableFormat, "pcie_link_width", (unsigned long long)metrics->pcie_link_width);
	printf(__tableFormat, "pcie_link_speed", (unsigned long long)metrics->pcie_link_speed);

	/* XGMI bus width and bitrate (in Gbps) */
	printf(__tableFormat, "xgmi_link_width", (unsigned long long)metrics->xgmi_link_width);
	printf(__tableFormat, "xgmi_link_speed", (unsigned long long)metrics->xgmi_link_speed);

	/* Utilization Accumulated (%) */
	printf(__tableFormat, "gfx_activity_acc", (unsigned long long)metrics->gfx_activity_acc);
	printf(__tableFormat, "mem_activity_acc", (unsigned long long)metrics->mem_activity_acc);

	/*PCIE accumulated bandwidth (GB/sec) */
	printf(__tableFormat, "pcie_bandwidth_acc", (unsigned long long)metrics->pcie_bandwidth_acc);

	/*PCIE instantaneous bandwidth (GB/sec) */
	printf(__tableFormat, "pcie_bandwidth_inst", (unsigned long long)metrics->pcie_bandwidth_inst);

	/* PCIE L0 to recovery state transition accumulated count */
	printf(__tableFormat, "pcie_l0_to_recov_count_acc", (unsigned long long)metrics->pcie_l0_to_recov_count_acc);

	/* PCIE replay accumulated count */
	printf(__tableFormat, "pcie_replay_count_acc", (unsigned long long)metrics->pcie_replay_count_acc);

	/* PCIE replay rollover accumulated count */
	printf(__tableFormat, "pcie_replay_rover_count_acc", (unsigned long long)metrics->pcie_replay_rover_count_acc);

	/* XGMI accumulated data transfer size(KiloBytes) */
	for (unsigned i = 0; i < NUM_XGMI_LINKS; i++)
	{
		sprintf(buf, "xgmi_read_data_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->xgmi_read_data_acc[i]);
	}
	for (unsigned i = 0; i < NUM_XGMI_LINKS; i++)
	{
		sprintf(buf, "xgmi_write_data_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->xgmi_write_data_acc[i]);
	}

	/* PMFW attached timestamp (10ns resolution) */
	printf(__tableFormat, "firmware_timestamp", (unsigned long long)metrics->firmware_timestamp);

	/* Current clocks (Mhz) */
	for (unsigned i = 0; i < MAX_GFX_CLKS; i++)
	{
		sprintf(buf, "current_gfxclk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_gfxclk[i]);
	}
	for (unsigned i = 0; i < MAX_CLKS; i++)
	{
		sprintf(buf, "current_socclk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_socclk[i]);
	}
	for (unsigned i = 0; i < MAX_CLKS; i++)
	{
		sprintf(buf, "current_vclk0[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_vclk0[i]);
	}
	for (unsigned i = 0; i < MAX_CLKS; i++)
	{
		sprintf(buf, "current_dclk0[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_dclk0[i]);
	}
	printf(__tableFormat, "current_uclk", (unsigned long long)metrics->current_uclk);

	printf(__tableFormat, "padding", (unsigned long long)metrics->padding);
}

static void __dump_gpu_metrics_v1_5(const struct gpu_metrics_v1_5 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	printf(__subStructFormat, "metrics_table_header", "common_header {");
	__dump_metrics_table_header(&metrics->common_header);
	printf(__subStructFormat, "", "}");

	/* Temperature (Celsius) */
	printf(__tableFormat, "temperature_hotspot", (unsigned long long)metrics->temperature_hotspot);
	printf(__tableFormat, "temperature_mem", (unsigned long long)metrics->temperature_mem);
	printf(__tableFormat, "temperature_vrsoc", (unsigned long long)metrics->temperature_vrsoc);

	/* Power (Watts) */
	printf(__tableFormat, "curr_socket_power", (unsigned long long)metrics->curr_socket_power);

	/* Utilization (%) */
	printf(__tableFormat, "average_gfx_activity", (unsigned long long)metrics->average_gfx_activity);
	printf(__tableFormat, "average_umc_activity", (unsigned long long)metrics->average_umc_activity); // memory controller
	for (unsigned i = 0; i < NUM_VCN; i++)
	{
		sprintf(buf, "vcn_activity[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->vcn_activity[i]);
	}
	for (unsigned i = 0; i < NUM_JPEG_ENG; i++)
	{
		sprintf(buf, "jpeg_activity[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->jpeg_activity[i]);
	}

	/* Energy (15.259uJ (2^-16) units) */
	printf(__tableFormat, "energy_accumulator", (unsigned long long)metrics->energy_accumulator);

	/* Driver attached timestamp (in ns) */
	printf(__tableFormat, "system_clock_counter", (unsigned long long)metrics->system_clock_counter);

	/* Throttle status */
	printf(__tableFormat, "throttle_status", (unsigned long long)metrics->throttle_status);

	/* Clock Lock Status. Each bit corresponds to clock instance */
	printf(__tableFormat, "gfxclk_lock_status", (unsigned long long)metrics->gfxclk_lock_status);

	/* Link width (number of lanes) and speed (in 0.1 GT/s) */
	printf(__tableFormat, "pcie_link_width", (unsigned long long)metrics->pcie_link_width);
	printf(__tableFormat, "pcie_link_speed", (unsigned long long)metrics->pcie_link_speed);

	/* XGMI bus width and bitrate (in Gbps) */
	printf(__tableFormat, "xgmi_link_width", (unsigned long long)metrics->xgmi_link_width);
	printf(__tableFormat, "xgmi_link_speed", (unsigned long long)metrics->xgmi_link_speed);

	/* Utilization Accumulated (%) */
	printf(__tableFormat, "gfx_activity_acc", (unsigned long long)metrics->gfx_activity_acc);
	printf(__tableFormat, "mem_activity_acc", (unsigned long long)metrics->mem_activity_acc);

	/*PCIE accumulated bandwidth (GB/sec) */
	printf(__tableFormat, "pcie_bandwidth_acc", (unsigned long long)metrics->pcie_bandwidth_acc);

	/*PCIE instantaneous bandwidth (GB/sec) */
	printf(__tableFormat, "pcie_bandwidth_inst", (unsigned long long)metrics->pcie_bandwidth_inst);

	/* PCIE L0 to recovery state transition accumulated count */
	printf(__tableFormat, "pcie_l0_to_recov_count_acc", (unsigned long long)metrics->pcie_l0_to_recov_count_acc);

	/* PCIE replay accumulated count */
	printf(__tableFormat, "pcie_replay_count_acc", (unsigned long long)metrics->pcie_replay_count_acc);

	/* PCIE replay rollover accumulated count */
	printf(__tableFormat, "pcie_replay_rover_count_acc", (unsigned long long)metrics->pcie_replay_rover_count_acc);

	/* PCIE NAK sent  accumulated count */
	printf(__tableFormat, "pcie_nak_sent_count_acc", (unsigned long long)metrics->pcie_nak_sent_count_acc);

	/* PCIE NAK received accumulated count */
	printf(__tableFormat, "pcie_nak_rcvd_count_acc", (unsigned long long)metrics->pcie_nak_rcvd_count_acc);

	/* XGMI accumulated data transfer size(KiloBytes) */
	for (unsigned i = 0; i < NUM_XGMI_LINKS; i++)
	{
		sprintf(buf, "xgmi_read_data_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->xgmi_read_data_acc[i]);
	}
	for (unsigned i = 0; i < NUM_XGMI_LINKS; i++)
	{
		sprintf(buf, "xgmi_write_data_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->xgmi_write_data_acc[i]);
	}

	/* PMFW attached timestamp (10ns resolution) */
	printf(__tableFormat, "firmware_timestamp", (unsigned long long)metrics->firmware_timestamp);

	/* Current clocks (Mhz) */
	for (unsigned i = 0; i < MAX_GFX_CLKS; i++)
	{
		sprintf(buf, "current_gfxclk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_gfxclk[i]);
	}
	for (unsigned i = 0; i < MAX_CLKS; i++)
	{
		sprintf(buf, "current_socclk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_socclk[i]);
	}
	for (unsigned i = 0; i < MAX_CLKS; i++)
	{
		sprintf(buf, "current_vclk0[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_vclk0[i]);
	}
	for (unsigned i = 0; i < MAX_CLKS; i++)
	{
		sprintf(buf, "current_dclk0[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_dclk0[i]);
	}
	printf(__tableFormat, "current_uclk", (unsigned long long)metrics->current_uclk);

	printf(__tableFormat, "padding", (unsigned long long)metrics->padding);
}

static void __dump_gpu_metrics_v1_6(const struct gpu_metrics_v1_6 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	printf(__subStructFormat, "metrics_table_header", "common_header {");
	__dump_metrics_table_header(&metrics->common_header);
	printf(__subStructFormat, "", "}");

	/* Temperature (Celsius) */
	printf(__tableFormat, "temperature_hotspot", (unsigned long long)metrics->temperature_hotspot);
	printf(__tableFormat, "temperature_mem", (unsigned long long)metrics->temperature_mem);
	printf(__tableFormat, "temperature_vrsoc", (unsigned long long)metrics->temperature_vrsoc);

	/* Power (Watts) */
	printf(__tableFormat, "curr_socket_power", (unsigned long long)metrics->curr_socket_power);

	/* Utilization (%) */
	printf(__tableFormat, "average_gfx_activity", (unsigned long long)metrics->average_gfx_activity);
	printf(__tableFormat, "average_umc_activity", (unsigned long long)metrics->average_umc_activity); // memory controller

	/* Energy (15.259uJ (2^-16) units) */
	printf(__tableFormat, "energy_accumulator", (unsigned long long)metrics->energy_accumulator);

	/* Driver attached timestamp (in ns) */
	printf(__tableFormat, "system_clock_counter", (unsigned long long)metrics->system_clock_counter);

	/* Accumulation cycle counter */
	printf(__tableFormat, "accumulation_counter", (unsigned long long)metrics->accumulation_counter);

	/* Accumulated throttler residencies */
	printf(__tableFormat, "prochot_residency_acc", (unsigned long long)metrics->prochot_residency_acc);
	printf(__tableFormat, "ppt_residency_acc", (unsigned long long)metrics->ppt_residency_acc);
	printf(__tableFormat, "socket_thm_residency_acc", (unsigned long long)metrics->socket_thm_residency_acc);
	printf(__tableFormat, "vr_thm_residency_acc", (unsigned long long)metrics->vr_thm_residency_acc);
	printf(__tableFormat, "hbm_thm_residency_acc", (unsigned long long)metrics->hbm_thm_residency_acc);

	/* Clock Lock Status. Each bit corresponds to clock instance */
	printf(__tableFormat, "gfxclk_lock_status", (unsigned long long)metrics->gfxclk_lock_status);

	/* Link width (number of lanes) and speed (in 0.1 GT/s) */
	printf(__tableFormat, "pcie_link_width", (unsigned long long)metrics->pcie_link_width);
	printf(__tableFormat, "pcie_link_speed", (unsigned long long)metrics->pcie_link_speed);

	/* XGMI bus width and bitrate (in Gbps) */
	printf(__tableFormat, "xgmi_link_width", (unsigned long long)metrics->xgmi_link_width);
	printf(__tableFormat, "xgmi_link_speed", (unsigned long long)metrics->xgmi_link_speed);

	/* Utilization Accumulated (%) */
	printf(__tableFormat, "gfx_activity_acc", (unsigned long long)metrics->gfx_activity_acc);
	printf(__tableFormat, "mem_activity_acc", (unsigned long long)metrics->mem_activity_acc);

	/*PCIE accumulated bandwidth (GB/sec) */
	printf(__tableFormat, "pcie_bandwidth_acc", (unsigned long long)metrics->pcie_bandwidth_acc);

	/*PCIE instantaneous bandwidth (GB/sec) */
	printf(__tableFormat, "pcie_bandwidth_inst", (unsigned long long)metrics->pcie_bandwidth_inst);

	/* PCIE L0 to recovery state transition accumulated count */
	printf(__tableFormat, "pcie_l0_to_recov_count_acc", (unsigned long long)metrics->pcie_l0_to_recov_count_acc);

	/* PCIE replay accumulated count */
	printf(__tableFormat, "pcie_replay_count_acc", (unsigned long long)metrics->pcie_replay_count_acc);

	/* PCIE replay rollover accumulated count */
	printf(__tableFormat, "pcie_replay_rover_count_acc", (unsigned long long)metrics->pcie_replay_rover_count_acc);

	/* PCIE NAK sent  accumulated count */
	printf(__tableFormat, "pcie_nak_sent_count_acc", (unsigned long long)metrics->pcie_nak_sent_count_acc);

	/* PCIE NAK received accumulated count */
	printf(__tableFormat, "pcie_nak_rcvd_count_acc", (unsigned long long)metrics->pcie_nak_rcvd_count_acc);

	/* XGMI accumulated data transfer size(KiloBytes) */
	for (unsigned i = 0; i < NUM_XGMI_LINKS; i++)
	{
		sprintf(buf, "xgmi_read_data_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->xgmi_read_data_acc[i]);
	}
	for (unsigned i = 0; i < NUM_XGMI_LINKS; i++)
	{
		sprintf(buf, "xgmi_write_data_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->xgmi_write_data_acc[i]);
	}

	/* PMFW attached timestamp (10ns resolution) */
	printf(__tableFormat, "firmware_timestamp", (unsigned long long)metrics->firmware_timestamp);

	/* Current clocks (Mhz) */
	for (unsigned i = 0; i < MAX_GFX_CLKS; i++)
	{
		sprintf(buf, "current_gfxclk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_gfxclk[i]);
	}
	for (unsigned i = 0; i < MAX_CLKS; i++)
	{
		sprintf(buf, "current_socclk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_socclk[i]);
	}
	for (unsigned i = 0; i < MAX_CLKS; i++)
	{
		sprintf(buf, "current_vclk0[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_vclk0[i]);
	}
	for (unsigned i = 0; i < MAX_CLKS; i++)
	{
		sprintf(buf, "current_dclk0[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_dclk0[i]);
	}
	printf(__tableFormat, "current_uclk", (unsigned long long)metrics->current_uclk);

	/* Number of current partition */
	printf(__tableFormat, "num_partition", (unsigned long long)metrics->num_partition);

	/* XCP metrics stats */
	for (unsigned i = 0; i < NUM_XCP; i++)
	{
		sprintf(buf, "xcp_stats[%u] {", i);
		printf(__subStructFormat, "amdgpu_xcp_metrics", buf);
		__dump_amdgpu_xcp_metrics(&metrics->xcp_stats[i]);
		printf(__subStructFormat, "", "}");
	}

	/* PCIE other end recovery counter */
	printf(__tableFormat, "pcie_lc_perf_other_end_recovery", (unsigned long long)metrics->pcie_lc_perf_other_end_recovery);
}

static void __dump_gpu_metrics_v1_7(const struct gpu_metrics_v1_7 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	printf(__subStructFormat, "metrics_table_header", "common_header {");
	__dump_metrics_table_header(&metrics->common_header);
	printf(__subStructFormat, "", "}");

	/* Temperature (Celsius) */
	printf(__tableFormat, "temperature_hotspot", (unsigned long long)metrics->temperature_hotspot);
	printf(__tableFormat, "temperature_mem", (unsigned long long)metrics->temperature_mem);
	printf(__tableFormat, "temperature_vrsoc", (unsigned long long)metrics->temperature_vrsoc);

	/* Power (Watts) */
	printf(__tableFormat, "curr_socket_power", (unsigned long long)metrics->curr_socket_power);

	/* Utilization (%) */
	printf(__tableFormat, "average_gfx_activity", (unsigned long long)metrics->average_gfx_activity);
	printf(__tableFormat, "average_umc_activity", (unsigned long long)metrics->average_umc_activity); // memory controller

	/* VRAM max bandwidthi (in GB/sec) at max memory clock */
	printf(__tableFormat, "mem_max_bandwidth", (unsigned long long)metrics->mem_max_bandwidth);

	/* Energy (15.259uJ (2^-16) units) */
	printf(__tableFormat, "energy_accumulator", (unsigned long long)metrics->energy_accumulator);

	/* Driver attached timestamp (in ns) */
	printf(__tableFormat, "system_clock_counter", (unsigned long long)metrics->system_clock_counter);

	/* Accumulation cycle counter */
	printf(__tableFormat, "accumulation_counter", (unsigned long long)metrics->accumulation_counter);

	/* Accumulated throttler residencies */
	printf(__tableFormat, "prochot_residency_acc", (unsigned long long)metrics->prochot_residency_acc);
	printf(__tableFormat, "ppt_residency_acc", (unsigned long long)metrics->ppt_residency_acc);
	printf(__tableFormat, "socket_thm_residency_acc", (unsigned long long)metrics->socket_thm_residency_acc);
	printf(__tableFormat, "vr_thm_residency_acc", (unsigned long long)metrics->vr_thm_residency_acc);
	printf(__tableFormat, "hbm_thm_residency_acc", (unsigned long long)metrics->hbm_thm_residency_acc);

	/* Clock Lock Status. Each bit corresponds to clock instance */
	printf(__tableFormat, "gfxclk_lock_status", (unsigned long long)metrics->gfxclk_lock_status);

	/* Link width (number of lanes) and speed (in 0.1 GT/s) */
	printf(__tableFormat, "pcie_link_width", (unsigned long long)metrics->pcie_link_width);
	printf(__tableFormat, "pcie_link_speed", (unsigned long long)metrics->pcie_link_speed);

	/* XGMI bus width and bitrate (in Gbps) */
	printf(__tableFormat, "xgmi_link_width", (unsigned long long)metrics->xgmi_link_width);
	printf(__tableFormat, "xgmi_link_speed", (unsigned long long)metrics->xgmi_link_speed);

	/* Utilization Accumulated (%) */
	printf(__tableFormat, "gfx_activity_acc", (unsigned long long)metrics->gfx_activity_acc);
	printf(__tableFormat, "mem_activity_acc", (unsigned long long)metrics->mem_activity_acc);

	/*PCIE accumulated bandwidth (GB/sec) */
	printf(__tableFormat, "pcie_bandwidth_acc", (unsigned long long)metrics->pcie_bandwidth_acc);

	/*PCIE instantaneous bandwidth (GB/sec) */
	printf(__tableFormat, "pcie_bandwidth_inst", (unsigned long long)metrics->pcie_bandwidth_inst);

	/* PCIE L0 to recovery state transition accumulated count */
	printf(__tableFormat, "pcie_l0_to_recov_count_acc", (unsigned long long)metrics->pcie_l0_to_recov_count_acc);

	/* PCIE replay accumulated count */
	printf(__tableFormat, "pcie_replay_count_acc", (unsigned long long)metrics->pcie_replay_count_acc);

	/* PCIE replay rollover accumulated count */
	printf(__tableFormat, "pcie_replay_rover_count_acc", (unsigned long long)metrics->pcie_replay_rover_count_acc);

	/* PCIE NAK sent  accumulated count */
	printf(__tableFormat, "pcie_nak_sent_count_acc", (unsigned long long)metrics->pcie_nak_sent_count_acc);

	/* PCIE NAK received accumulated count */
	printf(__tableFormat, "pcie_nak_rcvd_count_acc", (unsigned long long)metrics->pcie_nak_rcvd_count_acc);

	/* XGMI accumulated data transfer size(KiloBytes) */
	for (unsigned i = 0; i < NUM_XGMI_LINKS; i++)
	{
		sprintf(buf, "xgmi_read_data_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->xgmi_read_data_acc[i]);
	}
	for (unsigned i = 0; i < NUM_XGMI_LINKS; i++)
	{
		sprintf(buf, "xgmi_write_data_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->xgmi_write_data_acc[i]);
	}

	/* XGMI link status(active/inactive) */
	for (unsigned i = 0; i < NUM_XGMI_LINKS; i++)
	{
		sprintf(buf, "xgmi_link_status[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->xgmi_link_status[i]);
	}

	printf(__tableFormat, "padding", (unsigned long long)metrics->padding);

	/* PMFW attached timestamp (10ns resolution) */
	printf(__tableFormat, "firmware_timestamp", (unsigned long long)metrics->firmware_timestamp);

	/* Current clocks (Mhz) */
	for (unsigned i = 0; i < MAX_GFX_CLKS; i++)
	{
		sprintf(buf, "current_gfxclk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_gfxclk[i]);
	}
	for (unsigned i = 0; i < MAX_CLKS; i++)
	{
		sprintf(buf, "current_socclk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_socclk[i]);
	}
	for (unsigned i = 0; i < MAX_CLKS; i++)
	{
		sprintf(buf, "current_vclk0[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_vclk0[i]);
	}
	for (unsigned i = 0; i < MAX_CLKS; i++)
	{
		sprintf(buf, "current_dclk0[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_dclk0[i]);
	}
	printf(__tableFormat, "current_uclk", (unsigned long long)metrics->current_uclk);

	/* Number of current partition */
	printf(__tableFormat, "num_partition", (unsigned long long)metrics->num_partition);

	/* XCP metrics stats */
	for (unsigned i = 0; i < NUM_XCP; i++)
	{
		sprintf(buf, "xcp_stats[%u] {", i);
		printf(__subStructFormat, "amdgpu_xcp_metrics_v1_1", buf);
		__dump_amdgpu_xcp_metrics_v1_1(&metrics->xcp_stats[i]);
		printf(__subStructFormat, "", "}");
	}

	/* PCIE other end recovery counter */
	printf(__tableFormat, "pcie_lc_perf_other_end_recovery", (unsigned long long)metrics->pcie_lc_perf_other_end_recovery);
}

static void __dump_gpu_metrics_v1_8(const struct gpu_metrics_v1_8 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	printf(__subStructFormat, "metrics_table_header", "common_header {");
	__dump_metrics_table_header(&metrics->common_header);
	printf(__subStructFormat, "", "}");

	/* Temperature (Celsius) */
	printf(__tableFormat, "temperature_hotspot", (unsigned long long)metrics->temperature_hotspot);
	printf(__tableFormat, "temperature_mem", (unsigned long long)metrics->temperature_mem);
	printf(__tableFormat, "temperature_vrsoc", (unsigned long long)metrics->temperature_vrsoc);

	/* Power (Watts) */
	printf(__tableFormat, "curr_socket_power", (unsigned long long)metrics->curr_socket_power);

	/* Utilization (%) */
	printf(__tableFormat, "average_gfx_activity", (unsigned long long)metrics->average_gfx_activity);
	printf(__tableFormat, "average_umc_activity", (unsigned long long)metrics->average_umc_activity); // memory controller

	/* VRAM max bandwidthi (in GB/sec) at max memory clock */
	printf(__tableFormat, "mem_max_bandwidth", (unsigned long long)metrics->mem_max_bandwidth);

	/* Energy (15.259uJ (2^-16) units) */
	printf(__tableFormat, "energy_accumulator", (unsigned long long)metrics->energy_accumulator);

	/* Driver attached timestamp (in ns) */
	printf(__tableFormat, "system_clock_counter", (unsigned long long)metrics->system_clock_counter);

	/* Accumulation cycle counter */
	printf(__tableFormat, "accumulation_counter", (unsigned long long)metrics->accumulation_counter);

	/* Accumulated throttler residencies */
	printf(__tableFormat, "prochot_residency_acc", (unsigned long long)metrics->prochot_residency_acc);
	printf(__tableFormat, "ppt_residency_acc", (unsigned long long)metrics->ppt_residency_acc);
	printf(__tableFormat, "socket_thm_residency_acc", (unsigned long long)metrics->socket_thm_residency_acc);
	printf(__tableFormat, "vr_thm_residency_acc", (unsigned long long)metrics->vr_thm_residency_acc);
	printf(__tableFormat, "hbm_thm_residency_acc", (unsigned long long)metrics->hbm_thm_residency_acc);

	/* Clock Lock Status. Each bit corresponds to clock instance */
	printf(__tableFormat, "gfxclk_lock_status", (unsigned long long)metrics->gfxclk_lock_status);

	/* Link width (number of lanes) and speed (in 0.1 GT/s) */
	printf(__tableFormat, "pcie_link_width", (unsigned long long)metrics->pcie_link_width);
	printf(__tableFormat, "pcie_link_speed", (unsigned long long)metrics->pcie_link_speed);

	/* XGMI bus width and bitrate (in Gbps) */
	printf(__tableFormat, "xgmi_link_width", (unsigned long long)metrics->xgmi_link_width);
	printf(__tableFormat, "xgmi_link_speed", (unsigned long long)metrics->xgmi_link_speed);

	/* Utilization Accumulated (%) */
	printf(__tableFormat, "gfx_activity_acc", (unsigned long long)metrics->gfx_activity_acc);
	printf(__tableFormat, "mem_activity_acc", (unsigned long long)metrics->mem_activity_acc);

	/*PCIE accumulated bandwidth (GB/sec) */
	printf(__tableFormat, "pcie_bandwidth_acc", (unsigned long long)metrics->pcie_bandwidth_acc);

	/*PCIE instantaneous bandwidth (GB/sec) */
	printf(__tableFormat, "pcie_bandwidth_inst", (unsigned long long)metrics->pcie_bandwidth_inst);

	/* PCIE L0 to recovery state transition accumulated count */
	printf(__tableFormat, "pcie_l0_to_recov_count_acc", (unsigned long long)metrics->pcie_l0_to_recov_count_acc);

	/* PCIE replay accumulated count */
	printf(__tableFormat, "pcie_replay_count_acc", (unsigned long long)metrics->pcie_replay_count_acc);

	/* PCIE replay rollover accumulated count */
	printf(__tableFormat, "pcie_replay_rover_count_acc", (unsigned long long)metrics->pcie_replay_rover_count_acc);

	/* PCIE NAK sent  accumulated count */
	printf(__tableFormat, "pcie_nak_sent_count_acc", (unsigned long long)metrics->pcie_nak_sent_count_acc);

	/* PCIE NAK received accumulated count */
	printf(__tableFormat, "pcie_nak_rcvd_count_acc", (unsigned long long)metrics->pcie_nak_rcvd_count_acc);

	/* XGMI accumulated data transfer size(KiloBytes) */
	for (unsigned i = 0; i < NUM_XGMI_LINKS; i++)
	{
		sprintf(buf, "xgmi_read_data_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->xgmi_read_data_acc[i]);
	}
	for (unsigned i = 0; i < NUM_XGMI_LINKS; i++)
	{
		sprintf(buf, "xgmi_write_data_acc[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->xgmi_write_data_acc[i]);
	}

	/* XGMI link status(active/inactive) */
	for (unsigned i = 0; i < NUM_XGMI_LINKS; i++)
	{
		sprintf(buf, "xgmi_link_status[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->xgmi_link_status[i]);
	}

	printf(__tableFormat, "padding", (unsigned long long)metrics->padding);

	/* PMFW attached timestamp (10ns resolution) */
	printf(__tableFormat, "firmware_timestamp", (unsigned long long)metrics->firmware_timestamp);

	/* Current clocks (Mhz) */
	for (unsigned i = 0; i < MAX_GFX_CLKS; i++)
	{
		sprintf(buf, "current_gfxclk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_gfxclk[i]);
	}
	for (unsigned i = 0; i < MAX_CLKS; i++)
	{
		sprintf(buf, "current_socclk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_socclk[i]);
	}
	for (unsigned i = 0; i < MAX_CLKS; i++)
	{
		sprintf(buf, "current_vclk0[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_vclk0[i]);
	}
	for (unsigned i = 0; i < MAX_CLKS; i++)
	{
		sprintf(buf, "current_dclk0[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_dclk0[i]);
	}
	printf(__tableFormat, "current_uclk", (unsigned long long)metrics->current_uclk);

	/* Number of current partition */
	printf(__tableFormat, "num_partition", (unsigned long long)metrics->num_partition);

	/* XCP metrics stats */
	for (unsigned i = 0; i < NUM_XCP; i++)
	{
		sprintf(buf, "xcp_stats[%u] {", i);
		printf(__subStructFormat, "amdgpu_xcp_metrics_v1_2", buf);
		__dump_amdgpu_xcp_metrics_v1_2(&metrics->xcp_stats[i]);
		printf(__subStructFormat, "", "}");
	}

	/* PCIE other end recovery counter */
	printf(__tableFormat, "pcie_lc_perf_other_end_recovery", (unsigned long long)metrics->pcie_lc_perf_other_end_recovery);
}

static void __dump_gpu_metrics_v2_0(const struct gpu_metrics_v2_0 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	printf(__subStructFormat, "metrics_table_header", "common_header {");
	__dump_metrics_table_header(&metrics->common_header);
	printf(__subStructFormat, "", "}");

	/* Driver attached timestamp (in ns) */
	printf(__tableFormat, "system_clock_counter", (unsigned long long)metrics->system_clock_counter);

	/* Temperature */
	printf(__tableFormat, "temperature_gfx", (unsigned long long)metrics->temperature_gfx); // gfx temperature on APUs
	printf(__tableFormat, "temperature_soc", (unsigned long long)metrics->temperature_soc); // soc temperature on APUs
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "temperature_core[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->temperature_core[i]); // CPU core temperature on APUs
	}
	for (unsigned i = 0; i < 2; i++)
	{
		sprintf(buf, "temperature_l3[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->temperature_l3[i]);
	}

	/* Utilization */
	printf(__tableFormat, "average_gfx_activity", (unsigned long long)metrics->average_gfx_activity);
	printf(__tableFormat, "average_mm_activity", (unsigned long long)metrics->average_mm_activity); // UVD or VCN

	/* Power/Energy */
	printf(__tableFormat, "average_socket_power", (unsigned long long)metrics->average_socket_power); // dGPU + APU power on A + A platform
	printf(__tableFormat, "average_cpu_power", (unsigned long long)metrics->average_cpu_power);
	printf(__tableFormat, "average_soc_power", (unsigned long long)metrics->average_soc_power);
	printf(__tableFormat, "average_gfx_power", (unsigned long long)metrics->average_gfx_power);
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "average_core_power[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->average_core_power[i]); // CPU core power on APUs
	}

	/* Average clocks */
	printf(__tableFormat, "average_gfxclk_frequency", (unsigned long long)metrics->average_gfxclk_frequency);
	printf(__tableFormat, "average_socclk_frequency", (unsigned long long)metrics->average_socclk_frequency);
	printf(__tableFormat, "average_uclk_frequency", (unsigned long long)metrics->average_uclk_frequency);
	printf(__tableFormat, "average_fclk_frequency", (unsigned long long)metrics->average_fclk_frequency);
	printf(__tableFormat, "average_vclk_frequency", (unsigned long long)metrics->average_vclk_frequency);
	printf(__tableFormat, "average_dclk_frequency", (unsigned long long)metrics->average_dclk_frequency);

	/* Current clocks */
	printf(__tableFormat, "current_gfxclk", (unsigned long long)metrics->current_gfxclk);
	printf(__tableFormat, "current_socclk", (unsigned long long)metrics->current_socclk);
	printf(__tableFormat, "current_uclk", (unsigned long long)metrics->current_uclk);
	printf(__tableFormat, "current_fclk", (unsigned long long)metrics->current_fclk);
	printf(__tableFormat, "current_vclk", (unsigned long long)metrics->current_vclk);
	printf(__tableFormat, "current_dclk", (unsigned long long)metrics->current_dclk);
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "current_coreclk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_coreclk[i]); // CPU core clocks
	}
	for (unsigned i = 0; i < 2; i++)
	{
		sprintf(buf, "current_l3clk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_l3clk[i]);
	}

	/* Throttle status */
	printf(__tableFormat, "throttle_status", (unsigned long long)metrics->throttle_status);

	/* Fans */
	printf(__tableFormat, "fan_pwm", (unsigned long long)metrics->fan_pwm);

	printf(__tableFormat, "padding", (unsigned long long)metrics->padding);
}

static void __dump_gpu_metrics_v2_1(const struct gpu_metrics_v2_1 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	printf(__subStructFormat, "metrics_table_header", "common_header {");
	__dump_metrics_table_header(&metrics->common_header);
	printf(__subStructFormat, "", "}");

	/* Temperature */
	printf(__tableFormat, "temperature_gfx", (unsigned long long)metrics->temperature_gfx); // gfx temperature on APUs
	printf(__tableFormat, "temperature_soc", (unsigned long long)metrics->temperature_soc); // soc temperature on APUs
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "temperature_core[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->temperature_core[i]); // CPU core temperature on APUs
	}
	for (unsigned i = 0; i < 2; i++)
	{
		sprintf(buf, "temperature_l3[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->temperature_l3[i]);
	}

	/* Utilization */
	printf(__tableFormat, "average_gfx_activity", (unsigned long long)metrics->average_gfx_activity);
	printf(__tableFormat, "average_mm_activity", (unsigned long long)metrics->average_mm_activity); // UVD or VCN

	/* Driver attached timestamp (in ns) */
	printf(__tableFormat, "system_clock_counter", (unsigned long long)metrics->system_clock_counter);

	/* Power/Energy */
	printf(__tableFormat, "average_socket_power", (unsigned long long)metrics->average_socket_power); // dGPU + APU power on A + A platform
	printf(__tableFormat, "average_cpu_power", (unsigned long long)metrics->average_cpu_power);
	printf(__tableFormat, "average_soc_power", (unsigned long long)metrics->average_soc_power);
	printf(__tableFormat, "average_gfx_power", (unsigned long long)metrics->average_gfx_power);
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "average_core_power[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->average_core_power[i]); // CPU core power on APUs
	}

	/* Average clocks */
	printf(__tableFormat, "average_gfxclk_frequency", (unsigned long long)metrics->average_gfxclk_frequency);
	printf(__tableFormat, "average_socclk_frequency", (unsigned long long)metrics->average_socclk_frequency);
	printf(__tableFormat, "average_uclk_frequency", (unsigned long long)metrics->average_uclk_frequency);
	printf(__tableFormat, "average_fclk_frequency", (unsigned long long)metrics->average_fclk_frequency);
	printf(__tableFormat, "average_vclk_frequency", (unsigned long long)metrics->average_vclk_frequency);
	printf(__tableFormat, "average_dclk_frequency", (unsigned long long)metrics->average_dclk_frequency);

	/* Current clocks */
	printf(__tableFormat, "current_gfxclk", (unsigned long long)metrics->current_gfxclk);
	printf(__tableFormat, "current_socclk", (unsigned long long)metrics->current_socclk);
	printf(__tableFormat, "current_uclk", (unsigned long long)metrics->current_uclk);
	printf(__tableFormat, "current_fclk", (unsigned long long)metrics->current_fclk);
	printf(__tableFormat, "current_vclk", (unsigned long long)metrics->current_vclk);
	printf(__tableFormat, "current_dclk", (unsigned long long)metrics->current_dclk);
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "current_coreclk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_coreclk[i]); // CPU core clocks
	}
	for (unsigned i = 0; i < 2; i++)
	{
		sprintf(buf, "current_l3clk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_l3clk[i]);
	}

	/* Throttle status */
	printf(__tableFormat, "throttle_status", (unsigned long long)metrics->throttle_status);

	/* Fans */
	printf(__tableFormat, "fan_pwm", (unsigned long long)metrics->fan_pwm);

	for (unsigned i = 0; i < 3; i++)
	{
		sprintf(buf, "padding[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->padding[i]);
	}
}

static void __dump_gpu_metrics_v2_2(const struct gpu_metrics_v2_2 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	printf(__subStructFormat, "metrics_table_header", "common_header {");
	__dump_metrics_table_header(&metrics->common_header);
	printf(__subStructFormat, "", "}");

	/* Temperature */
	printf(__tableFormat, "temperature_gfx", (unsigned long long)metrics->temperature_gfx); // gfx temperature on APUs
	printf(__tableFormat, "temperature_soc", (unsigned long long)metrics->temperature_soc); // soc temperature on APUs
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "temperature_core[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->temperature_core[i]); // CPU core temperature on APUs
	}
	for (unsigned i = 0; i < 2; i++)
	{
		sprintf(buf, "temperature_l3[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->temperature_l3[i]);
	}

	/* Utilization */
	printf(__tableFormat, "average_gfx_activity", (unsigned long long)metrics->average_gfx_activity);
	printf(__tableFormat, "average_mm_activity", (unsigned long long)metrics->average_mm_activity); // UVD or VCN

	/* Driver attached timestamp (in ns) */
	printf(__tableFormat, "system_clock_counter", (unsigned long long)metrics->system_clock_counter);

	/* Power/Energy */
	printf(__tableFormat, "average_socket_power", (unsigned long long)metrics->average_socket_power); // dGPU + APU power on A + A platform
	printf(__tableFormat, "average_cpu_power", (unsigned long long)metrics->average_cpu_power);
	printf(__tableFormat, "average_soc_power", (unsigned long long)metrics->average_soc_power);
	printf(__tableFormat, "average_gfx_power", (unsigned long long)metrics->average_gfx_power);
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "average_core_power[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->average_core_power[i]); // CPU core power on APUs
	}

	/* Average clocks */
	printf(__tableFormat, "average_gfxclk_frequency", (unsigned long long)metrics->average_gfxclk_frequency);
	printf(__tableFormat, "average_socclk_frequency", (unsigned long long)metrics->average_socclk_frequency);
	printf(__tableFormat, "average_uclk_frequency", (unsigned long long)metrics->average_uclk_frequency);
	printf(__tableFormat, "average_fclk_frequency", (unsigned long long)metrics->average_fclk_frequency);
	printf(__tableFormat, "average_vclk_frequency", (unsigned long long)metrics->average_vclk_frequency);
	printf(__tableFormat, "average_dclk_frequency", (unsigned long long)metrics->average_dclk_frequency);

	/* Current clocks */
	printf(__tableFormat, "current_gfxclk", (unsigned long long)metrics->current_gfxclk);
	printf(__tableFormat, "current_socclk", (unsigned long long)metrics->current_socclk);
	printf(__tableFormat, "current_uclk", (unsigned long long)metrics->current_uclk);
	printf(__tableFormat, "current_fclk", (unsigned long long)metrics->current_fclk);
	printf(__tableFormat, "current_vclk", (unsigned long long)metrics->current_vclk);
	printf(__tableFormat, "current_dclk", (unsigned long long)metrics->current_dclk);
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "current_coreclk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_coreclk[i]); // CPU core clocks
	}
	for (unsigned i = 0; i < 2; i++)
	{
		sprintf(buf, "current_l3clk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_l3clk[i]);
	}

	/* Throttle status (ASIC dependent) */
	printf(__tableFormat, "throttle_status", (unsigned long long)metrics->throttle_status);

	/* Fans */
	printf(__tableFormat, "fan_pwm", (unsigned long long)metrics->fan_pwm);

	for (unsigned i = 0; i < 3; i++)
	{
		sprintf(buf, "padding[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->padding[i]);
	}

	/* Throttle status (ASIC independent) */
	printf(__tableFormat, "indep_throttle_status", (unsigned long long)metrics->indep_throttle_status);
}

static void __dump_gpu_metrics_v2_3(const struct gpu_metrics_v2_3 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	printf(__subStructFormat, "metrics_table_header", "common_header {");
	__dump_metrics_table_header(&metrics->common_header);
	printf(__subStructFormat, "", "}");

	/* Temperature */
	printf(__tableFormat, "temperature_gfx", (unsigned long long)metrics->temperature_gfx); // gfx temperature on APUs
	printf(__tableFormat, "temperature_soc", (unsigned long long)metrics->temperature_soc); // soc temperature on APUs
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "temperature_core[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->temperature_core[i]); // CPU core temperature on APUs
	}
	for (unsigned i = 0; i < 2; i++)
	{
		sprintf(buf, "temperature_l3[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->temperature_l3[i]);
	}

	/* Utilization */
	printf(__tableFormat, "average_gfx_activity", (unsigned long long)metrics->average_gfx_activity);
	printf(__tableFormat, "average_mm_activity", (unsigned long long)metrics->average_mm_activity); // UVD or VCN

	/* Driver attached timestamp (in ns) */
	printf(__tableFormat, "system_clock_counter", (unsigned long long)metrics->system_clock_counter);

	/* Power/Energy */
	printf(__tableFormat, "average_socket_power", (unsigned long long)metrics->average_socket_power); // dGPU + APU power on A + A platform
	printf(__tableFormat, "average_cpu_power", (unsigned long long)metrics->average_cpu_power);
	printf(__tableFormat, "average_soc_power", (unsigned long long)metrics->average_soc_power);
	printf(__tableFormat, "average_gfx_power", (unsigned long long)metrics->average_gfx_power);
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "average_core_power[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->average_core_power[i]); // CPU core power on APUs
	}

	/* Average clocks */
	printf(__tableFormat, "average_gfxclk_frequency", (unsigned long long)metrics->average_gfxclk_frequency);
	printf(__tableFormat, "average_socclk_frequency", (unsigned long long)metrics->average_socclk_frequency);
	printf(__tableFormat, "average_uclk_frequency", (unsigned long long)metrics->average_uclk_frequency);
	printf(__tableFormat, "average_fclk_frequency", (unsigned long long)metrics->average_fclk_frequency);
	printf(__tableFormat, "average_vclk_frequency", (unsigned long long)metrics->average_vclk_frequency);
	printf(__tableFormat, "average_dclk_frequency", (unsigned long long)metrics->average_dclk_frequency);

	/* Current clocks */
	printf(__tableFormat, "current_gfxclk", (unsigned long long)metrics->current_gfxclk);
	printf(__tableFormat, "current_socclk", (unsigned long long)metrics->current_socclk);
	printf(__tableFormat, "current_uclk", (unsigned long long)metrics->current_uclk);
	printf(__tableFormat, "current_fclk", (unsigned long long)metrics->current_fclk);
	printf(__tableFormat, "current_vclk", (unsigned long long)metrics->current_vclk);
	printf(__tableFormat, "current_dclk", (unsigned long long)metrics->current_dclk);
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "current_coreclk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_coreclk[i]); // CPU core clocks
	}
	for (unsigned i = 0; i < 2; i++)
	{
		sprintf(buf, "current_l3clk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_l3clk[i]);
	}

	/* Throttle status (ASIC dependent) */
	printf(__tableFormat, "throttle_status", (unsigned long long)metrics->throttle_status);

	/* Fans */
	printf(__tableFormat, "fan_pwm", (unsigned long long)metrics->fan_pwm);

	for (unsigned i = 0; i < 3; i++)
	{
		sprintf(buf, "padding[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->padding[i]);
	}

	/* Throttle status (ASIC independent) */
	printf(__tableFormat, "indep_throttle_status", (unsigned long long)metrics->indep_throttle_status);

	/* Average Temperature */
	printf(__tableFormat, "average_temperature_gfx", (unsigned long long)metrics->average_temperature_gfx); // average gfx temperature on APUs
	printf(__tableFormat, "average_temperature_soc", (unsigned long long)metrics->average_temperature_soc); // average soc temperature on APUs
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "average_temperature_core[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->average_temperature_core[i]); // average CPU core temperature on APUs
	}
	for (unsigned i = 0; i < 2; i++)
	{
		sprintf(buf, "average_temperature_l3[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->average_temperature_l3[i]);
	}
}

static void __dump_gpu_metrics_v2_4(const struct gpu_metrics_v2_4 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	printf(__subStructFormat, "metrics_table_header", "common_header {");
	__dump_metrics_table_header(&metrics->common_header);
	printf(__subStructFormat, "", "}");

	/* Temperature (unit: centi-Celsius) */
	printf(__tableFormat, "temperature_gfx", (unsigned long long)metrics->temperature_gfx);
	printf(__tableFormat, "temperature_soc", (unsigned long long)metrics->temperature_soc);
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "temperature_core[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->temperature_core[i]);
	}
	for (unsigned i = 0; i < 2; i++)
	{
		sprintf(buf, "temperature_l3[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->temperature_l3[i]);
	}

	/* Utilization (unit: centi) */
	printf(__tableFormat, "average_gfx_activity", (unsigned long long)metrics->average_gfx_activity);
	printf(__tableFormat, "average_mm_activity", (unsigned long long)metrics->average_mm_activity);

	/* Driver attached timestamp (in ns) */
	printf(__tableFormat, "system_clock_counter", (unsigned long long)metrics->system_clock_counter);

	/* Power/Energy (unit: mW) */
	printf(__tableFormat, "average_socket_power", (unsigned long long)metrics->average_socket_power);
	printf(__tableFormat, "average_cpu_power", (unsigned long long)metrics->average_cpu_power);
	printf(__tableFormat, "average_soc_power", (unsigned long long)metrics->average_soc_power);
	printf(__tableFormat, "average_gfx_power", (unsigned long long)metrics->average_gfx_power);
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "average_core_power[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->average_core_power[i]);
	}

	/* Average clocks (unit: MHz) */
	printf(__tableFormat, "average_gfxclk_frequency", (unsigned long long)metrics->average_gfxclk_frequency);
	printf(__tableFormat, "average_socclk_frequency", (unsigned long long)metrics->average_socclk_frequency);
	printf(__tableFormat, "average_uclk_frequency", (unsigned long long)metrics->average_uclk_frequency);
	printf(__tableFormat, "average_fclk_frequency", (unsigned long long)metrics->average_fclk_frequency);
	printf(__tableFormat, "average_vclk_frequency", (unsigned long long)metrics->average_vclk_frequency);
	printf(__tableFormat, "average_dclk_frequency", (unsigned long long)metrics->average_dclk_frequency);

	/* Current clocks (unit: MHz) */
	printf(__tableFormat, "current_gfxclk", (unsigned long long)metrics->current_gfxclk);
	printf(__tableFormat, "current_socclk", (unsigned long long)metrics->current_socclk);
	printf(__tableFormat, "current_uclk", (unsigned long long)metrics->current_uclk);
	printf(__tableFormat, "current_fclk", (unsigned long long)metrics->current_fclk);
	printf(__tableFormat, "current_vclk", (unsigned long long)metrics->current_vclk);
	printf(__tableFormat, "current_dclk", (unsigned long long)metrics->current_dclk);
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "current_coreclk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_coreclk[i]);
	}
	for (unsigned i = 0; i < 2; i++)
	{
		sprintf(buf, "current_l3clk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_l3clk[i]);
	}

	/* Throttle status (ASIC dependent) */
	printf(__tableFormat, "throttle_status", (unsigned long long)metrics->throttle_status);

	/* Fans */
	printf(__tableFormat, "fan_pwm", (unsigned long long)metrics->fan_pwm);

	for (unsigned i = 0; i < 3; i++)
	{
		sprintf(buf, "padding[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->padding[i]);
	}

	/* Throttle status (ASIC independent) */
	printf(__tableFormat, "indep_throttle_status", (unsigned long long)metrics->indep_throttle_status);

	/* Average Temperature (unit: centi-Celsius) */
	printf(__tableFormat, "average_temperature_gfx", (unsigned long long)metrics->average_temperature_gfx);
	printf(__tableFormat, "average_temperature_soc", (unsigned long long)metrics->average_temperature_soc);
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "average_temperature_core[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->average_temperature_core[i]);
	}
	for (unsigned i = 0; i < 2; i++)
	{
		sprintf(buf, "average_temperature_l3[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->average_temperature_l3[i]);
	}

	/* Power/Voltage (unit: mV) */
	printf(__tableFormat, "average_cpu_voltage", (unsigned long long)metrics->average_cpu_voltage);
	printf(__tableFormat, "average_soc_voltage", (unsigned long long)metrics->average_soc_voltage);
	printf(__tableFormat, "average_gfx_voltage", (unsigned long long)metrics->average_gfx_voltage);

	/* Power/Current (unit: mA) */
	printf(__tableFormat, "average_cpu_current", (unsigned long long)metrics->average_cpu_current);
	printf(__tableFormat, "average_soc_current", (unsigned long long)metrics->average_soc_current);
	printf(__tableFormat, "average_gfx_current", (unsigned long long)metrics->average_gfx_current);
}

static void __dump_gpu_metrics_v3_0(const struct gpu_metrics_v3_0 *metrics)
{
	char __attribute__((unused)) buf[64] = "";

	printf(__subStructFormat, "metrics_table_header", "common_header {");
	__dump_metrics_table_header(&metrics->common_header);
	printf(__subStructFormat, "", "}");

	/* Temperature */
	/* gfx temperature on APUs */
	printf(__tableFormat, "temperature_gfx", (unsigned long long)metrics->temperature_gfx);
	/* soc temperature on APUs */
	printf(__tableFormat, "temperature_soc", (unsigned long long)metrics->temperature_soc);
	/* CPU core temperature on APUs */
	for (unsigned i = 0; i < 16; i++)
	{
		sprintf(buf, "temperature_core[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->temperature_core[i]);
	}
	/* skin temperature on APUs */
	printf(__tableFormat, "temperature_skin", (unsigned long long)metrics->temperature_skin);

	/* Utilization */
	/* time filtered GFX busy % [0-100] */
	printf(__tableFormat, "average_gfx_activity", (unsigned long long)metrics->average_gfx_activity);
	/* time filtered VCN busy % [0-100] */
	printf(__tableFormat, "average_vcn_activity", (unsigned long long)metrics->average_vcn_activity);
	/* time filtered IPU per-column busy % [0-100] */
	for (unsigned i = 0; i < 8; i++)
	{
		sprintf(buf, "average_ipu_activity[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->average_ipu_activity[i]);
	}
	/* time filtered per-core C0 residency % [0-100]*/
	for (unsigned i = 0; i < 16; i++)
	{
		sprintf(buf, "average_core_c0_activity[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->average_core_c0_activity[i]);
	}
	/* time filtered DRAM read bandwidth [MB/sec] */
	printf(__tableFormat, "average_dram_reads", (unsigned long long)metrics->average_dram_reads);
	/* time filtered DRAM write bandwidth [MB/sec] */
	printf(__tableFormat, "average_dram_writes", (unsigned long long)metrics->average_dram_writes);
	/* time filtered IPU read bandwidth [MB/sec] */
	printf(__tableFormat, "average_ipu_reads", (unsigned long long)metrics->average_ipu_reads);
	/* time filtered IPU write bandwidth [MB/sec] */
	printf(__tableFormat, "average_ipu_writes", (unsigned long long)metrics->average_ipu_writes);

	/* Driver attached timestamp (in ns) */
	printf(__tableFormat, "system_clock_counter", (unsigned long long)metrics->system_clock_counter);

	/* Power/Energy */
	/* time filtered power used for PPT/STAPM [APU+dGPU] [mW] */
	printf(__tableFormat, "average_socket_power", (unsigned long long)metrics->average_socket_power);
	/* time filtered IPU power [mW] */
	printf(__tableFormat, "average_ipu_power", (unsigned long long)metrics->average_ipu_power);
	/* time filtered APU power [mW] */
	printf(__tableFormat, "average_apu_power", (unsigned long long)metrics->average_apu_power);
	/* time filtered GFX power [mW] */
	printf(__tableFormat, "average_gfx_power", (unsigned long long)metrics->average_gfx_power);
	/* time filtered dGPU power [mW] */
	printf(__tableFormat, "average_dgpu_power", (unsigned long long)metrics->average_dgpu_power);
	/* time filtered sum of core power across all cores in the socket [mW] */
	printf(__tableFormat, "average_all_core_power", (unsigned long long)metrics->average_all_core_power);
	/* calculated core power [mW] */
	for (unsigned i = 0; i < 16; i++)
	{
		sprintf(buf, "average_core_power[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->average_core_power[i]);
	}
	/* time filtered total system power [mW] */
	printf(__tableFormat, "average_sys_power", (unsigned long long)metrics->average_sys_power);
	/* maximum IRM defined STAPM power limit [mW] */
	printf(__tableFormat, "stapm_power_limit", (unsigned long long)metrics->stapm_power_limit);
	/* time filtered STAPM power limit [mW] */
	printf(__tableFormat, "current_stapm_power_limit", (unsigned long long)metrics->current_stapm_power_limit);

	/* time filtered clocks [MHz] */
	printf(__tableFormat, "average_gfxclk_frequency", (unsigned long long)metrics->average_gfxclk_frequency);
	printf(__tableFormat, "average_socclk_frequency", (unsigned long long)metrics->average_socclk_frequency);
	printf(__tableFormat, "average_vpeclk_frequency", (unsigned long long)metrics->average_vpeclk_frequency);
	printf(__tableFormat, "average_ipuclk_frequency", (unsigned long long)metrics->average_ipuclk_frequency);
	printf(__tableFormat, "average_fclk_frequency", (unsigned long long)metrics->average_fclk_frequency);
	printf(__tableFormat, "average_vclk_frequency", (unsigned long long)metrics->average_vclk_frequency);
	printf(__tableFormat, "average_uclk_frequency", (unsigned long long)metrics->average_uclk_frequency);
	printf(__tableFormat, "average_mpipu_frequency", (unsigned long long)metrics->average_mpipu_frequency);

	/* Current clocks */
	/* target core frequency [MHz] */
	for (unsigned i = 0; i < 16; i++)
	{
		sprintf(buf, "current_coreclk[%u]", i);
		printf(__tableFormat, buf, (unsigned long long)metrics->current_coreclk[i]);
	}
	/* CCLK frequency limit enforced on classic cores [MHz] */
	printf(__tableFormat, "current_core_maxfreq", (unsigned long long)metrics->current_core_maxfreq);
	/* GFXCLK frequency limit enforced on GFX [MHz] */
	printf(__tableFormat, "current_gfx_maxfreq", (unsigned long long)metrics->current_gfx_maxfreq);

	/* Throttle Residency (ASIC dependent) */
	printf(__tableFormat, "throttle_residency_prochot", (unsigned long long)metrics->throttle_residency_prochot);
	printf(__tableFormat, "throttle_residency_spl", (unsigned long long)metrics->throttle_residency_spl);
	printf(__tableFormat, "throttle_residency_fppt", (unsigned long long)metrics->throttle_residency_fppt);
	printf(__tableFormat, "throttle_residency_sppt", (unsigned long long)metrics->throttle_residency_sppt);
	printf(__tableFormat, "throttle_residency_thm_core", (unsigned long long)metrics->throttle_residency_thm_core);
	printf(__tableFormat, "throttle_residency_thm_gfx", (unsigned long long)metrics->throttle_residency_thm_gfx);
	printf(__tableFormat, "throttle_residency_thm_soc", (unsigned long long)metrics->throttle_residency_thm_soc);

	/* Metrics table alpha filter time constant [us] */
	printf(__tableFormat, "time_filter_alphavalue", (unsigned long long)metrics->time_filter_alphavalue);
}

int dump_gpu_metrics(const void *metrics)
{
	struct metrics_table_header *header = (struct metrics_table_header *)metrics;

	printf(__tableHeader);

	switch ((header->format_revision << 8) | header->content_revision)
	{
	case (1 << 8) | 0:
		__dump_gpu_metrics_v1_0((struct gpu_metrics_v1_0 *)metrics);
		break;
	case (1 << 8) | 1:
		__dump_gpu_metrics_v1_1((struct gpu_metrics_v1_1 *)metrics);
		break;
	case (1 << 8) | 2:
		__dump_gpu_metrics_v1_2((struct gpu_metrics_v1_2 *)metrics);
		break;
	case (1 << 8) | 3:
		__dump_gpu_metrics_v1_3((struct gpu_metrics_v1_3 *)metrics);
		break;
	case (1 << 8) | 4:
		__dump_gpu_metrics_v1_4((struct gpu_metrics_v1_4 *)metrics);
		break;
	case (1 << 8) | 5:
		__dump_gpu_metrics_v1_5((struct gpu_metrics_v1_5 *)metrics);
		break;
	case (1 << 8) | 6:
		__dump_gpu_metrics_v1_6((struct gpu_metrics_v1_6 *)metrics);
		break;
	case (1 << 8) | 7:
		__dump_gpu_metrics_v1_7((struct gpu_metrics_v1_7 *)metrics);
		break;
	case (1 << 8) | 8:
		__dump_gpu_metrics_v1_8((struct gpu_metrics_v1_8 *)metrics);
		break;
	case (2 << 8) | 0:
		__dump_gpu_metrics_v2_0((struct gpu_metrics_v2_0 *)metrics);
		break;
	case (2 << 8) | 1:
		__dump_gpu_metrics_v2_1((struct gpu_metrics_v2_1 *)metrics);
		break;
	case (2 << 8) | 2:
		__dump_gpu_metrics_v2_2((struct gpu_metrics_v2_2 *)metrics);
		break;
	case (2 << 8) | 3:
		__dump_gpu_metrics_v2_3((struct gpu_metrics_v2_3 *)metrics);
		break;
	case (2 << 8) | 4:
		__dump_gpu_metrics_v2_4((struct gpu_metrics_v2_4 *)metrics);
		break;
	case (3 << 8) | 0:
		__dump_gpu_metrics_v3_0((struct gpu_metrics_v3_0 *)metrics);
		break;
	default:
		return -1;
	}
	return 0;
}
